import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "../components/ui/theme-provider";
import { SiteFooter } from "@/components/ui/site-footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next Apps",
  description: "Generated by create next app",
};

export default function RootLayout({children,}: Readonly<{children: React.ReactNode;}>) {
  return (
    <html lang="en" >
      <ThemeProvider
        attribute="class"
          defaultTheme="zinc"
          enableSystem
          disableTransitionOnChange
      >
        <body className={inter.className}>{children}</body>
      </ThemeProvider>
      <SiteFooter />
    </html>
  );
}
