import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "./components/theme-provider";
import { SiteFooter } from "./components/site-footer";
import { SiteHeader } from "./components/site-header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next Apps",
  description: "Generated by create next app",
};

export default function RootLayout({ children, }: Readonly<{ children: React.ReactNode; }>) {
  return (
    <html lang="en" >
      <ThemeProvider
        attribute="class"
        defaultTheme="zinc"
        enableSystem
        disableTransitionOnChange
      >
        <body className={inter.className}>
          <SiteHeader />
          {children}
          <SiteFooter />
        </body>
      </ThemeProvider>
    </html>
  );
}
